### PR TITLE
Reactivate slave syncer

### LINKED ISSUE #586: tlog : reactivate slave syncer
slave syncer hasn't been maintained since long time ago as the other side of it (nbd part) also being disabled.
We need to reactivate (and maintain) it since we will use this feature again.

We can only start it after #475 finished.

### PR DESCRIPTION
**Pull request by iwanbk**
Fixes #586 

The main goal of this PR is to only re-activate the slave syncer feature.
It also do some refactoring to improve the code as the old code is unnecessary complex and outdated.

### CODE REVIEW

**Comment by iwanbk** [comment]
new feature, redesign, and any other improvements will be addressed at #587  or #596

**Comment by GlenDC** [comment]
Blocked by #596.

**Comment by iwanbk** [comment]
> Blocked by #596.

I think you misunderstood my comment at https://github.com/zero-os/0-Disk/issues/596#issuecomment-343033099.

It is not this PR that should be blocked, but #587.
This PR should be not blocked because there is no point to block it. It mainly contains two things:
- refactor current code
- reactivate slave syncer (which is only small code in main.go) -> if you want, i can undo this change

**Comment by iwanbk** [comment]
> reactivate slave syncer (which is only small code in main.go) -> if you want, i can undo this change

I have disabled this code, so i think it is good to be merged.

**Pull request merged**
