### PR TITLE
integrate hotreloader into tlog's redis pool

### LINKED ISSUE #177: tlogserver: support SIGHUP reloading for config hot reloading
For the solution of issue #170, the config is only loaded at startup time. For long running tlogservers however it would also require it to support hot-reloading (eg at SIGHUP).

### PR DESCRIPTION
**Pull request by GlenDC**
Fixes #177.

### CODE REVIEW

**Comment by GlenDC** [comment]
Travis failed because of the same reason as #252, restarted the specific `TIMEOUT=5m make testcgo` jobs, should make it pass.

**Comment by GlenDC** [comment]
All test pass, ready for review @iwanbk :)

**Comment by iwanbk** [comment]
Does this change affect the tlog's flusher?

**Comment by GlenDC** [comment]
In a way, but not in a way that you should be able to notice. It simply reloads the config, when receiving a SIGHUP, and applies that to the redisPools which are active.

For long running servers, this allows for data to migrate to different storage clusters, and let the server know about it.

But it shouldn't really affect you, no.

**Comment by iwanbk** [comment]
> In a way, but not in a way that you should be able to notice. It simply reloads the config, when receiving a SIGHUP, and applies that to the redisPools which are active.

Oh, i thought we need to do something to the tlog's flusher, like:
- restart flusher
- re-assign the flusher's pool  variable because it is not pointer

**Comment by GlenDC** [comment]
Nope, because the reloading happens, within that `tlog.redisPool`, IFF we use the config-based redis pool. If you for example use the `-memorystorage` or `tlogrpc` flags, you would use a static redisPool instead. But in production it is assumed that the config version is used (`-config` flag, which also has a default=`./config.yml`).

**Comment by iwanbk** [comment]
cool

**Pull request merged**
