### PR TITLE
nbdserver tlogStorage : `go test -race` fixes

### PR DESCRIPTION
**Pull request by iwanbk**
part of #239

### CODE REVIEW

**Comment by iwanbk** [comment]
99e77d464a8becd06bdecab85f7ba0153feb3ffa is fix attempt of 
```
WARNING: DATA RACE
Write at 0x00c427fca918 by goroutine 480:
  sync/atomic.CompareAndSwapInt32()
      /home/ibk/go/src/runtime/race_amd64.s:293 +0xb
  sync.(*Mutex).Lock()
      /home/ibk/go/src/sync/mutex.go:48 +0x4d
  context.(*cancelCtx).cancel()
      /home/ibk/go/src/context/context.go:341 +0x6c
  context.WithCancel.func1()
      /home/ibk/go/src/context/context.go:232 +0x78
  github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).Close()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:224 +0xb7
  github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorage()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:206 +0x1261
  github.com/zero-os/0-Disk/nbdserver/ardb.testTlogStorage()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:212 +0x242
  github.com/zero-os/0-Disk/nbdserver/ardb.TestTlogStorageWithDeduped()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:80 +0x1cc
  testing.tRunner()
      /home/ibk/go/src/testing/testing.go:657 +0x107

Previous write at 0x00c427fca918 by goroutine 63:
  context.WithCancel()
      /home/ibk/go/src/context/context.go:230 +0x157
  github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).GoBackground()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:254 +0x1cc

Goroutine 480 (running) created at:
  testing.(*T).Run()
      /home/ibk/go/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /home/ibk/go/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /home/ibk/go/src/testing/testing.go:657 +0x107
  testing.runTests()
      /home/ibk/go/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /home/ibk/go/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/zero-os/0-Disk/nbdserver/ardb/_test/_testmain.go:90 +0x20f

Goroutine 63 (running) created at:
  github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorage()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:76 +0xe6
  github.com/zero-os/0-Disk/nbdserver/ardb.testTlogStorage()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:212 +0x242
  github.com/zero-os/0-Disk/nbdserver/ardb.TestTlogStorageWithDeduped()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:80 +0x1cc
  testing.tRunner()
      /home/ibk/go/src/testing/testing.go:657 +0x107
```

**Comment by iwanbk** [comment]
5b89664e47fa41d2556161c79967bb9add7aac2b is fix attempt of below data races log.

From the log,  `Set`, `Merge`, and `flushCached` content might happen in the same time.
We need to protect it with lock
```
WARNING: DATA RACE
Write at 0x00c427398b82 by goroutine 1064:
  runtime.slicecopy()
      /home/ibk/go/src/runtime/slice.go:160 +0x0
  github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).Merge()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:155 +0x17f
  github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorageDeadlock.func2()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:497 +0x37e

Previous read at 0x00c427398b80 by goroutine 1072:
  runtime.slicecopy()
      /home/ibk/go/src/runtime/slice.go:160 +0x0
  github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).Set()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:119 +0x3e2
  github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).Merge()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:158 +0x1bb
  github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorageDeadlock.func2()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:497 +0x37e

Goroutine 1064 (running) created at:
  github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorageDeadlock()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:501 +0x61b
  github.com/zero-os/0-Disk/nbdserver/ardb.testTlogStorageDeadlock()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:240 +0x25c
  github.com/zero-os/0-Disk/nbdserver/ardb.TestTlogStorageDeadlockWithNondeduped()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:198 +0x25b
  testing.tRunner()
      /home/ibk/go/src/testing/testing.go:657 +0x107

Goroutine 1072 (finished) created at:
  github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorageDeadlock()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:501 +0x61b
  github.com/zero-os/0-Disk/nbdserver/ardb.testTlogStorageDeadlock()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:240 +0x25c
  github.com/zero-os/0-Disk/nbdserver/ardb.TestTlogStorageDeadlockWithNondeduped()
      /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:198 +0x25b
  testing.tRunner()
```

```
WARNING: DATA RACE
  Read at 0x00c4296a7200 by goroutine 751:
    runtime.slicecopy()
        /home/ibk/go/src/runtime/slice.go:160 +0x0
    bufio.(*Writer).Write()
        /home/ibk/go/src/bufio/bufio.go:610 +0x431
    github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis.(*conn).writeBytes()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis/conn.go:334 +0x95
    github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis.(*conn).writeCommand()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis/conn.go:358 +0x3a4
    github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis.(*conn).Do()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis/conn.go:581 +0x7f8
    github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis.(*pooledConnection).Do()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/vendor/github.com/garyburd/redigo/redis/pool.go:400 +0x12d
    github.com/zero-os/0-Disk/nbdserver/ardb.(*nonDedupedStorage).Set()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/nondeduped.go:48 +0x667
    github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).flushCachedContent()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:366 +0x288
    github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).GoBackground()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:290 +0x4a3

  Previous write at 0x00c4296a7207 by goroutine 1032:
    runtime.slicecopy()
        /home/ibk/go/src/runtime/slice.go:160 +0x0
    github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).merge()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:175 +0x182
    github.com/zero-os/0-Disk/nbdserver/ardb.(*tlogStorage).Merge()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog.go:149 +0xdc
    github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorageDeadlock.func2()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:497 +0x37e

  Goroutine 751 (running) created at:
    github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorageDeadlock()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:431 +0xec
    github.com/zero-os/0-Disk/nbdserver/ardb.testTlogStorageDeadlock()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:240 +0x25c
    github.com/zero-os/0-Disk/nbdserver/ardb.TestTlogStorageDeadlockWithNondeduped()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:198 +0x25b
    testing.tRunner()
        /home/ibk/go/src/testing/testing.go:657 +0x107

  Goroutine 1032 (running) created at:
    github.com/zero-os/0-Disk/nbdserver/ardb.testBackendStorageDeadlock()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/ardb_test.go:501 +0x61b
    github.com/zero-os/0-Disk/nbdserver/ardb.testTlogStorageDeadlock()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:240 +0x25c
    github.com/zero-os/0-Disk/nbdserver/ardb.TestTlogStorageDeadlockWithNondeduped()
        /home/ibk/pathgo/src/github.com/zero-os/0-Disk/nbdserver/ardb/tlog_test.go:198 +0x25b
    testing.tRunner()
        /home/ibk/go/src/testing/testing.go:657 +0x107
```

**Comment by iwanbk** [comment]
It seems that above 2 commits make the nbdserver pass the  ` go test  -race -run ^TestTlog`  test.
We can't sure because `-race` flag doesn't always catch the race condition

**Comment by iwanbk** [comment]
it also passed this test
```
go test -race -run ^TestAggressiveInMemorySequenceCacheEviction &&  go test -race -run ^TestInMemory && go test -race -run TestDataHistory
```

**Comment by iwanbk** [comment]
@GlenDC i think we might be able to remove `storageMux` lock?

**Comment by GlenDC** [comment]
@iwanbk yeah if you're going for this approach, we can remove both the `storageMux`. Also as you now make `tlogStorage` completely thread-safe, right from the complete top, we don't even require the sequenceCache to be thread safe any longer, so the mutex there can be gone as well... I do wonder, is it really nececary to lock it this high in the order? This makes the `tlogStorage` a bit slower, no?

**Comment by iwanbk** [comment]
>  I do wonder, is it really nececary to lock it this high in the order?

No, more fine grained lock is of course better.
I do this because this is what i can do **at the moment**, and i need it to be race free. Feel free to improve it.

> This makes the tlogStorage a bit slower, no?

Yep,

**Comment by GlenDC** [comment]
> No, more fine grained lock is of course better. I do this because this is what i can do at the moment, and i need it to be race free. Feel free to improve it.

Fair enough, going to accept it like this then. We can improve it later if tlogStorage starts to be too slow.

**Comment by GlenDC** [comment]
+ Rebased master into this PR's branch;
+ Enabled `-race` in Makefile's test targets (e9cce47), confirming that the entire codebase is now race free (at least as far as we know because of our test code);
+ Removed deprecated fine grained locks, as these would only slow things down (by a tiny bit), without serving any purpose in this new `tlogStorage` version (17fd8e9);

**Comment by GlenDC** [comment]
Restore go tests seem to keep failing on travis, but I have no idea why at the moment, as I don't see any clue in the travis log:

```
go test -race -timeout 5m github.com/zero-os/0-Disk github.com/zero-os/0-Disk/config github.com/zero-os/0-Disk/docs/assets github.com/zero-os/0-Disk/gonbdserver github.com/zero-os/0-Disk/gonbdserver/nbd github.com/zero-os/0-Disk/log github.com/zero-os/0-Disk/nbdserver github.com/zero-os/0-Disk/nbdserver/ardb github.com/zero-os/0-Disk/nbdserver/lba github.com/zero-os/0-Disk/redisstub github.com/zero-os/0-Disk/storagecluster github.com/zero-os/0-Disk/tlog github.com/zero-os/0-Disk/tlog/schema github.com/zero-os/0-Disk/tlog/tlogclient github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer github.com/zero-os/0-Disk/tlog/tlogclient/decoder github.com/zero-os/0-Disk/tlog/tlogclient/examples/send_tlog github.com/zero-os/0-Disk/tlog/tlogclient/examples/walk_history github.com/zero-os/0-Disk/tlog/tlogserver github.com/zero-os/0-Disk/tlog/tlogserver/erasure github.com/zero-os/0-Disk/tlog/tlogserver/server github.com/zero-os/0-Disk/zeroctl github.com/zero-os/0-Disk/zeroctl/cmd github.com/zero-os/0-Disk/zeroctl/cmd/config github.com/zero-os/0-Disk/zeroctl/cmd/copyvdisk github.com/zero-os/0-Disk/zeroctl/cmd/delvdisk github.com/zero-os/0-Disk/zeroctl/cmd/list github.com/zero-os/0-Disk/zeroctl/cmd/restore
ok  	github.com/zero-os/0-Disk	1.034s
ok  	github.com/zero-os/0-Disk/config	1.046s
?   	github.com/zero-os/0-Disk/docs/assets	[no test files]
?   	github.com/zero-os/0-Disk/gonbdserver	[no test files]
ok  	github.com/zero-os/0-Disk/gonbdserver/nbd	124.719s
?   	github.com/zero-os/0-Disk/log	[no test files]
?   	github.com/zero-os/0-Disk/nbdserver	[no test files]
ok  	github.com/zero-os/0-Disk/nbdserver/ardb	62.498s
ok  	github.com/zero-os/0-Disk/nbdserver/lba	1.050s
?   	github.com/zero-os/0-Disk/redisstub	[no test files]
ok  	github.com/zero-os/0-Disk/storagecluster	1.044s
ok  	github.com/zero-os/0-Disk/tlog	1.061s
?   	github.com/zero-os/0-Disk/tlog/schema	[no test files]
ok  	github.com/zero-os/0-Disk/tlog/tlogclient	13.535s
?   	github.com/zero-os/0-Disk/tlog/tlogclient/blockbuffer	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogclient/decoder	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogclient/examples/send_tlog	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogclient/examples/walk_history	[no test files]
?   	github.com/zero-os/0-Disk/tlog/tlogserver	[no test files]
ok  	github.com/zero-os/0-Disk/tlog/tlogserver/erasure	1.012s [no tests to run]
ok  	github.com/zero-os/0-Disk/tlog/tlogserver/server	14.729s
?   	github.com/zero-os/0-Disk/zeroctl	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/config	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/copyvdisk	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/delvdisk	[no test files]
?   	github.com/zero-os/0-Disk/zeroctl/cmd/list	[no test files]
t=2017-06-05T14:33:56+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:46180" module=global caller=redis.go:47
t=2017-06-05T14:33:56+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:37700" module=global caller=redis.go:47
t=2017-06-05T14:33:56+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:35668" module=global caller=redis.go:47
t=2017-06-05T14:33:56+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:41498" module=global caller=redis.go:47
t=2017-06-05T14:33:56+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:38997" module=global caller=redis.go:47
t=2017-06-05T14:33:56+0000 lvl=info msg="Started listening on local address 127.0.0.1:36146" module=global caller=server.go:55
t=2017-06-05T14:33:56+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:34416" module=global caller=redis.go:47
t=2017-06-05T14:33:56+0000 lvl=info msg="embedded LedisDB Server ready and listening at 127.0.0.1:35947" module=global caller=redis.go:47
t=2017-06-05T14:33:56+0000 lvl=info msg="loading storage cluster config" module=storagecluster caller=cluster.go:272
t=2017-06-05T14:33:56+0000 lvl=dbug msg="Loaded storagecluster 'mycluster' configuration (1 servers)" module=global caller=cluster.go:339
t=2017-06-05T14:33:56+0000 lvl=info msg="ready to reload StorageClusterConfig upon SIGHUP receival for:myvdisk" module=storagecluster caller=cluster.go:234
FAIL	github.com/zero-os/0-Disk/zeroctl/cmd/restore	3.640s
make: *** [testgo] Error 1
The command "TIMEOUT=5m make testgo" exited with 2.
Done. Your build exited with 1.
```

**Comment by GlenDC** [comment]
Seems that this is only ever an issue when running `testEndToEndReplay`, which somehow gets killed due to: `signal: killed`, ONLY when you run that test with the `-race` flag.

> see: https://travis-ci.org/zero-os/0-Disk/builds/239664773

So I don't think this is an issue on our side, and more to do with limitations on the travis machine, as doing a `-race` test on an EndToEnd test is probably very heavy.

Therefore I added the `-race` tests now as a seperate Make target, called `testrace`, which only runs on the `gonbdserver`, `nbdserver`, and `tlog` modules, using pure go. This should be good enough for now. It's certainly better then before, which wasn't running at all.

**Pull request merged**
