### PR TITLE
remove need of IYO environment variable to run tests

### LINKED ISSUE #457: make tlog tests work without need for iyo env variables
Currently one cannot run any tests which create a 0-stor client, without defining _valid_ values for the three `iyo` variables: `iyo_organization`, `iyo_client_id` and `iyo_secret`.

0-Stor seems to use a PEM certificate and public key for this, as can be seen in:
+ https://github.com/zero-os/0-stor/blob/master/client/client_test.go#L27
+ https://github.com/zero-os/0-stor/blob/master/client/client_test.go#L68

That could be a solution. Either way, we need something so travis and developers can run tests again without requiring to set environment variables.

### PR DESCRIPTION
**Pull request by zaibon**
fixes #457

### CODE REVIEW

**Comment by zaibon** [comment]
It's a actually more tricky then that cause after removing the IYO credentials, I have other tests failing. Mostly because of the validation of the tlog config. I need to spent bit more time knowing the code

**Comment by GlenDC** [comment]
@zaibon can you please also prune the vendor folder after updating it (`dev prune`), just make sure that you undo the deletion of `vendor/zombiezen.com/go/capnproto2/capnpc-go` and `vendor/zombiezen.com/go/capnproto2/std/go.capnp`, as we need those, even though they get pruned automatically.

Because right now you added a lot of extra files in the vendor folder which we don't require at all.

**Comment by GlenDC** [comment]
Also please rebase master into this branch and resolve the conflicts.

**Comment by GlenDC** [comment]
> It's a actually more tricky then that cause after removing the IYO credentials, I have other tests failing. Mostly because of the validation of the tlog config. I need to spent bit more time knowing the code

No worries, let me know when it's ready for another review.

**Comment by iwanbk** [comment]
> It's a actually more tricky then that cause after removing the IYO credentials, I have other tests failing. Mostly because of the validation of the tlog config. I need to spent bit more time knowing the code

It seems because you replace below code (and other similar code) to empty string.
```go
os.Getenv("iyo_organization")
```
random value should work i guess

**Comment by GlenDC** [comment]
Why you do a merge? This is a feature branch, would have been cleaner to simply do a rebase & force-push. You're the only one on this branch so it's possible.

**Comment by zaibon** [comment]
The only conflict I had was in the vendor. I tried to rebase, it made a huge mess.

**Comment by GlenDC** [comment]
> The only conflict I had was in the vendor. I tried to rebase, it made a huge mess.

OK... but either way, as part of that rebase you could have dropped that vendor update, as the update to 0-Stor on master is newer anyhow.

**Comment by zaibon** [comment]
no that was the problem, the one from master was not newer, that's why I had to do it here too.
Let me remove this merge commit, and clean it up

**Comment by zaibon** [comment]
@GlenDC have a look again ;-)

**Comment by GlenDC** [comment]
Unit tests pass as well, does it mean that it's ready for a final review @zaibon?

**Comment by zaibon** [comment]
yep

**Comment by GlenDC** [comment]
@zaibon can you also delete the environment variables from travis?

**Comment by zaibon** [comment]
@GlenDC yep no problem

**Comment by zaibon** [comment]
> @zaibon can you also delete the environment variables from travis?

Done

**Pull request merged**
